aligner_path: /usr/bin/minimap2
fast5: /home/salvador/Documents/ivt/fast5
fastq: /home/salvador/Documents/ivt/ivt_sup.fastq
geluster_path: /home/salvador/Documents/NanoRNA-ClusteringPipeline/tools/GeLuster/GeLuster
multi_to_single_fast5_path: /home/salvador/Documents/NanoRNA-ClusteringPipeline/env/bin/multi_to_single_fast5
nanopolish_path: /home/salvador/Documents/NanoRNA-ClusteringPipeline/tools/nanopolish/nanopolish
output: /home/salvador/Documents/pipeline_runs
pycoqc_path: /home/salvador/Documents/NanoRNA-ClusteringPipeline/env/bin/pycoQC
reference: /home/salvador/Documents/23rRNA.fa
samtools_path: /usr/bin/samtools
sequencing_summary: /home/salvador/Documents/ivt/sequencing_summary.txt
sorted_bam: /home/salvador/Documents/pipeline_runs/20240716_224835_output/alignment/ivt_sup.sorted.bam
threads: 10
