# Substitute the paths with the correct paths to both programs and inputs/outputs

# To obtain the path for a program use which "program_name" to find the program/dependency. 

fast5: /path/to/your/fast5/files
fastq: /path/to/your/combined.fastq
reference: /path/to/your/reference.fasta
output: /path/to/output/directory
multi_to_single_fast5_path: /path/to/multi_to_single_fast5
nanopolish_path: /path/to/nanopolish
aligner_path: /path/to/minimap2
pycoqc_path: /path/to/pycoQC
geluster_path: /path/to/Geluster
sequencing_summary: /path/to/sequencing_summary.txt #This file is obtained from the basecalling.
bam: path/to/bam.bam # This file is obtained from original basecalling to reference sequence.
threads: 4 # Default threads
